// Mocks generated by Mockito 5.4.4 from annotations
// in flow_state/test/ui/add_course/add_course_modal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flow_state/data/models/course.dart' as _i2;
import 'package:flow_state/data/models/video.dart' as _i6;
import 'package:flow_state/data/repositories/course_repository.dart' as _i5;
import 'package:flow_state/data/services/youtube_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourse_0 extends _i1.SmartFake implements _i2.Course {
  _FakeCourse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YouTubeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockYouTubeService extends _i1.Mock implements _i3.YouTubeService {
  @override
  _i4.Future<_i2.Course> extractCourse(String? url) => (super.noSuchMethod(
        Invocation.method(
          #extractCourse,
          [url],
        ),
        returnValue: _i4.Future<_i2.Course>.value(_FakeCourse_0(
          this,
          Invocation.method(
            #extractCourse,
            [url],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Course>.value(_FakeCourse_0(
          this,
          Invocation.method(
            #extractCourse,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.Course>);
}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i5.CourseRepository {
  @override
  List<_i2.Course> getAllCourses() => (super.noSuchMethod(
        Invocation.method(
          #getAllCourses,
          [],
        ),
        returnValue: <_i2.Course>[],
        returnValueForMissingStub: <_i2.Course>[],
      ) as List<_i2.Course>);

  @override
  _i4.Future<void> addCourse(_i2.Course? course) => (super.noSuchMethod(
        Invocation.method(
          #addCourse,
          [course],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCourse(_i2.Course? course) => (super.noSuchMethod(
        Invocation.method(
          #updateCourse,
          [course],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCourse(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCourse,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVideoProgress(
    String? courseId,
    String? videoId,
    int? positionSeconds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVideoProgress,
          [
            courseId,
            videoId,
            positionSeconds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createEmptyCourse(String? title) => (super.noSuchMethod(
        Invocation.method(
          #createEmptyCourse,
          [title],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addResourceToCourse(
    String? courseId,
    String? content,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addResourceToCourse,
          [
            courseId,
            content,
            type,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addVideoToCourse(
    String? courseId,
    _i6.Video? video,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVideoToCourse,
          [
            courseId,
            video,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
