// Mocks generated by Mockito 5.4.4 from annotations
// in flow_state/test/ui/player/video_player_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flow_state/data/models/course.dart' as _i3;
import 'package:flow_state/data/models/session.dart' as _i7;
import 'package:flow_state/data/models/video.dart' as _i5;
import 'package:flow_state/data/repositories/analytics_repository.dart' as _i6;
import 'package:flow_state/data/repositories/course_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i2.CourseRepository {
  @override
  List<_i3.Course> getAllCourses() => (super.noSuchMethod(
        Invocation.method(
          #getAllCourses,
          [],
        ),
        returnValue: <_i3.Course>[],
        returnValueForMissingStub: <_i3.Course>[],
      ) as List<_i3.Course>);

  @override
  _i4.Future<void> addCourse(_i3.Course? course) => (super.noSuchMethod(
        Invocation.method(
          #addCourse,
          [course],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCourse(_i3.Course? course) => (super.noSuchMethod(
        Invocation.method(
          #updateCourse,
          [course],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCourse(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCourse,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateVideoProgress(
    String? courseId,
    String? videoId,
    int? positionSeconds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVideoProgress,
          [
            courseId,
            videoId,
            positionSeconds,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> createEmptyCourse(String? title) => (super.noSuchMethod(
        Invocation.method(
          #createEmptyCourse,
          [title],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addResourceToCourse(
    String? courseId,
    String? content,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addResourceToCourse,
          [
            courseId,
            content,
            type,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addVideoToCourse(
    String? courseId,
    _i5.Video? video,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addVideoToCourse,
          [
            courseId,
            video,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepository extends _i1.Mock
    implements _i6.AnalyticsRepository {
  @override
  _i4.Future<void> logSession(int? durationSeconds) => (super.noSuchMethod(
        Invocation.method(
          #logSession,
          [durationSeconds],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i7.Session> getSessionsSince(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getSessionsSince,
          [date],
        ),
        returnValue: <_i7.Session>[],
        returnValueForMissingStub: <_i7.Session>[],
      ) as List<_i7.Session>);
}
