// Mocks generated by Mockito 5.4.4 from annotations
// in flow_state/test/data/services/youtube_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:collection' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/common/common.dart' as _i8;
import 'package:youtube_explode_dart/src/playlists/playlist.dart' as _i7;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/playlists/playlist_id.dart' as _i10;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/src/videos/videos.dart' as _i6;
import 'package:youtube_explode_dart/src/youtube_explode_base.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamClient_4 extends _i1.SmartFake implements _i6.StreamClient {
  _FakeStreamClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClosedCaptionClient_5 extends _i1.SmartFake
    implements _i6.ClosedCaptionClient {
  _FakeClosedCaptionClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsClient_6 extends _i1.SmartFake
    implements _i6.CommentsClient {
  _FakeCommentsClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideo_7 extends _i1.SmartFake implements _i6.Video {
  _FakeVideo_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylist_8 extends _i1.SmartFake implements _i7.Playlist {
  _FakePlaylist_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoId_9 extends _i1.SmartFake implements _i6.VideoId {
  _FakeVideoId_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelId_10 extends _i1.SmartFake implements _i4.ChannelId {
  _FakeChannelId_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThumbnailSet_11 extends _i1.SmartFake implements _i8.ThumbnailSet {
  _FakeThumbnailSet_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_12<E> extends _i1.SmartFake
    implements _i9.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEngagement_13 extends _i1.SmartFake implements _i8.Engagement {
  _FakeEngagement_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$VideoCopyWith_14<$Res> extends _i1.SmartFake
    implements _i6.$VideoCopyWith<$Res> {
  _Fake$VideoCopyWith_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistId_15 extends _i1.SmartFake implements _i10.PlaylistId {
  _FakePlaylistId_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PlaylistCopyWith_16<$Res> extends _i1.SmartFake
    implements _i7.$PlaylistCopyWith<$Res> {
  _Fake$PlaylistCopyWith_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ChannelCopyWith_17<$Res> extends _i1.SmartFake
    implements _i4.$ChannelCopyWith<$Res> {
  _Fake$ChannelCopyWith_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i11.YoutubeExplode {
  @override
  _i2.VideoClient get videos => (super.noSuchMethod(
        Invocation.getter(#videos),
        returnValue: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
        returnValueForMissingStub: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
      ) as _i2.VideoClient);

  @override
  set videos(_i2.VideoClient? _videos) => super.noSuchMethod(
        Invocation.setter(
          #videos,
          _videos,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PlaylistClient get playlists => (super.noSuchMethod(
        Invocation.getter(#playlists),
        returnValue: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
        returnValueForMissingStub: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
      ) as _i3.PlaylistClient);

  @override
  set playlists(_i3.PlaylistClient? _playlists) => super.noSuchMethod(
        Invocation.setter(
          #playlists,
          _playlists,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ChannelClient get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
        returnValueForMissingStub: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i4.ChannelClient);

  @override
  set channels(_i4.ChannelClient? _channels) => super.noSuchMethod(
        Invocation.setter(
          #channels,
          _channels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.SearchClient get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
        returnValueForMissingStub: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
      ) as _i5.SearchClient);

  @override
  set search(_i5.SearchClient? _search) => super.noSuchMethod(
        Invocation.setter(
          #search,
          _search,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VideoClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoClient extends _i1.Mock implements _i2.VideoClient {
  @override
  _i6.StreamClient get streamsClient => (super.noSuchMethod(
        Invocation.getter(#streamsClient),
        returnValue: _FakeStreamClient_4(
          this,
          Invocation.getter(#streamsClient),
        ),
        returnValueForMissingStub: _FakeStreamClient_4(
          this,
          Invocation.getter(#streamsClient),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.ClosedCaptionClient get closedCaptions => (super.noSuchMethod(
        Invocation.getter(#closedCaptions),
        returnValue: _FakeClosedCaptionClient_5(
          this,
          Invocation.getter(#closedCaptions),
        ),
        returnValueForMissingStub: _FakeClosedCaptionClient_5(
          this,
          Invocation.getter(#closedCaptions),
        ),
      ) as _i6.ClosedCaptionClient);

  @override
  _i6.CommentsClient get commentsClient => (super.noSuchMethod(
        Invocation.getter(#commentsClient),
        returnValue: _FakeCommentsClient_6(
          this,
          Invocation.getter(#commentsClient),
        ),
        returnValueForMissingStub: _FakeCommentsClient_6(
          this,
          Invocation.getter(#commentsClient),
        ),
      ) as _i6.CommentsClient);

  @override
  _i6.StreamClient get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakeStreamClient_4(
          this,
          Invocation.getter(#streams),
        ),
        returnValueForMissingStub: _FakeStreamClient_4(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.CommentsClient get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsClient_6(
          this,
          Invocation.getter(#comments),
        ),
        returnValueForMissingStub: _FakeCommentsClient_6(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i6.CommentsClient);

  @override
  _i12.Future<_i6.Video> get(dynamic videoId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [videoId],
        ),
        returnValue: _i12.Future<_i6.Video>.value(_FakeVideo_7(
          this,
          Invocation.method(
            #get,
            [videoId],
          ),
        )),
        returnValueForMissingStub: _i12.Future<_i6.Video>.value(_FakeVideo_7(
          this,
          Invocation.method(
            #get,
            [videoId],
          ),
        )),
      ) as _i12.Future<_i6.Video>);

  @override
  _i12.Future<_i6.RelatedVideosList?> getRelatedVideos(_i6.Video? video) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedVideos,
          [video],
        ),
        returnValue: _i12.Future<_i6.RelatedVideosList?>.value(),
        returnValueForMissingStub: _i12.Future<_i6.RelatedVideosList?>.value(),
      ) as _i12.Future<_i6.RelatedVideosList?>);
}

/// A class which mocks [PlaylistClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistClient extends _i1.Mock implements _i3.PlaylistClient {
  @override
  _i12.Future<_i7.Playlist> get(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i12.Future<_i7.Playlist>.value(_FakePlaylist_8(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i12.Future<_i7.Playlist>.value(_FakePlaylist_8(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i12.Future<_i7.Playlist>);

  @override
  _i12.Stream<_i6.Video> getVideos(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [id],
        ),
        returnValue: _i12.Stream<_i6.Video>.empty(),
        returnValueForMissingStub: _i12.Stream<_i6.Video>.empty(),
      ) as _i12.Stream<_i6.Video>);
}

/// A class which mocks [Video].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideo extends _i1.Mock implements _i6.Video {
  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  bool get hasWatchPage => (super.noSuchMethod(
        Invocation.getter(#hasWatchPage),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.VideoId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeVideoId_9(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakeVideoId_9(
          this,
          Invocation.getter(#id),
        ),
      ) as _i6.VideoId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get author => (super.noSuchMethod(
        Invocation.getter(#author),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
      ) as String);

  @override
  _i4.ChannelId get channelId => (super.noSuchMethod(
        Invocation.getter(#channelId),
        returnValue: _FakeChannelId_10(
          this,
          Invocation.getter(#channelId),
        ),
        returnValueForMissingStub: _FakeChannelId_10(
          this,
          Invocation.getter(#channelId),
        ),
      ) as _i4.ChannelId);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  _i8.ThumbnailSet get thumbnails => (super.noSuchMethod(
        Invocation.getter(#thumbnails),
        returnValue: _FakeThumbnailSet_11(
          this,
          Invocation.getter(#thumbnails),
        ),
        returnValueForMissingStub: _FakeThumbnailSet_11(
          this,
          Invocation.getter(#thumbnails),
        ),
      ) as _i8.ThumbnailSet);

  @override
  _i9.UnmodifiableListView<String> get keywords => (super.noSuchMethod(
        Invocation.getter(#keywords),
        returnValue: _FakeUnmodifiableListView_12<String>(
          this,
          Invocation.getter(#keywords),
        ),
        returnValueForMissingStub: _FakeUnmodifiableListView_12<String>(
          this,
          Invocation.getter(#keywords),
        ),
      ) as _i9.UnmodifiableListView<String>);

  @override
  _i8.Engagement get engagement => (super.noSuchMethod(
        Invocation.getter(#engagement),
        returnValue: _FakeEngagement_13(
          this,
          Invocation.getter(#engagement),
        ),
        returnValueForMissingStub: _FakeEngagement_13(
          this,
          Invocation.getter(#engagement),
        ),
      ) as _i8.Engagement);

  @override
  bool get isLive => (super.noSuchMethod(
        Invocation.getter(#isLive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<({String? album, String? artist, Uri? image, String? song})>
      get musicData => (super.noSuchMethod(
            Invocation.getter(#musicData),
            returnValue: <({
              String? album,
              String? artist,
              Uri? image,
              String? song
            })>[],
            returnValueForMissingStub: <({
              String? album,
              String? artist,
              Uri? image,
              String? song
            })>[],
          ) as List<
              ({String? album, String? artist, Uri? image, String? song})>);

  @override
  _i6.$VideoCopyWith<_i6.Video> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$VideoCopyWith_14<_i6.Video>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$VideoCopyWith_14<_i6.Video>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i6.$VideoCopyWith<_i6.Video>);
}

/// A class which mocks [Playlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylist extends _i1.Mock implements _i7.Playlist {
  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  _i10.PlaylistId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePlaylistId_15(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakePlaylistId_15(
          this,
          Invocation.getter(#id),
        ),
      ) as _i10.PlaylistId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get author => (super.noSuchMethod(
        Invocation.getter(#author),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  _i8.ThumbnailSet get thumbnails => (super.noSuchMethod(
        Invocation.getter(#thumbnails),
        returnValue: _FakeThumbnailSet_11(
          this,
          Invocation.getter(#thumbnails),
        ),
        returnValueForMissingStub: _FakeThumbnailSet_11(
          this,
          Invocation.getter(#thumbnails),
        ),
      ) as _i8.ThumbnailSet);

  @override
  _i8.Engagement get engagement => (super.noSuchMethod(
        Invocation.getter(#engagement),
        returnValue: _FakeEngagement_13(
          this,
          Invocation.getter(#engagement),
        ),
        returnValueForMissingStub: _FakeEngagement_13(
          this,
          Invocation.getter(#engagement),
        ),
      ) as _i8.Engagement);

  @override
  _i7.$PlaylistCopyWith<_i7.Playlist> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$PlaylistCopyWith_16<_i7.Playlist>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$PlaylistCopyWith_16<_i7.Playlist>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i7.$PlaylistCopyWith<_i7.Playlist>);
}

/// A class which mocks [Channel].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannel extends _i1.Mock implements _i4.Channel {
  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  _i4.ChannelId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeChannelId_10(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakeChannelId_10(
          this,
          Invocation.getter(#id),
        ),
      ) as _i4.ChannelId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get logoUrl => (super.noSuchMethod(
        Invocation.getter(#logoUrl),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#logoUrl),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#logoUrl),
        ),
      ) as String);

  @override
  String get bannerUrl => (super.noSuchMethod(
        Invocation.getter(#bannerUrl),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#bannerUrl),
        ),
        returnValueForMissingStub: _i13.dummyValue<String>(
          this,
          Invocation.getter(#bannerUrl),
        ),
      ) as String);

  @override
  _i4.$ChannelCopyWith<_i4.Channel> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ChannelCopyWith_17<_i4.Channel>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$ChannelCopyWith_17<_i4.Channel>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i4.$ChannelCopyWith<_i4.Channel>);
}
